# Generated by Django 4.2.6 on 2023-10-18 19:13

from django.db import migrations

def load_initial_data(apps, schema_editor):
    book_model = apps.get_model('api_app', 'Book')
    book_model.objects.create (
        title = "The Woman in Me", 
        author = "Britney Spears",
        description = "A superstar has it all but finds herself trapped."
        )
    book_model.objects.create (
        title = "The Firm", 
        author = "John Grisham",
        description = "The 'dream job' turns out not to be so dreamy."
        )
    book_model.objects.create (
        title = "Pride and Prejudice", 
        author = "Jane Austen",
        description = "A love story in the English countryside."
        )
    book_model.objects.create (
        title = "Great Expectations", 
        author = "Charles Dickens",
        description = "Making your way in the world today takes everything you've got."
        )
    book_model.objects.create (
        title = "Frankenstein", 
        author = "Mary Shelley",
        description = "A manufactured monster comes to life."
        )
    book_model.objects.create (
        title = "Atonement", 
        author = "Ian McEwan",
        description = "A love story turned tragic by war and lies."
        )

class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_alter_book_author_alter_book_title'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
